@startuml DatabaseObjects

' Variable Definition DB 
object "ZDAB_C_VARDEF_A - Variable Definition" as ZDAB_C_VARDEF_A { 
  *variable_id
  variable_name
  variable_class_handler
  is_vh_detected
  s_admin_data
}

' Module Configuration DB
object "ZDAB_C_MODCF_A - Module Config" as ZDAB_C_MODCF_A {
    *module_id
    module_name
    is_active
    s_admin_data
}

' Parameter Configuration DB
object "ZDAB_C_PRMCF_A - Parameter Config" as ZDAB_C_PRMCF_A {
    *module_id
    *param_id
    param_descr
    variable_id
}

' Parameter Value Configuration DB
object "ZDAB_C_PRMVLCF_A - Parameter Value Config" as ZDAB_C_PRMVLCF_A {
    *module_id
    *param_id
    *param_condition
    param_value
    param_value_4_value_help
}

ZDAB_C_MODCF_A --* ZDAB_C_PRMCF_A
ZDAB_C_PRMCF_A --* ZDAB_C_PRMVLCF_A
ZDAB_C_VARDEF_A ..* ZDAB_C_PRMCF_A

@enduml